### ISSUE TITLE
see less feature

### ISSUE THREAD

**Issue by Antuaaan** [apploft/ExpandableLabel#10]
I have just one expandableLabel and the 'see more" function works perfectly. Is it possible to add a "see less" function now that will return the label to its original state?

**Comment by michaelkamphausen** [comment]
It should be possible. You'll need to fork the project and add the feature yourself.

**Comment by Antuaaan** [comment]
I am busy trying to do that, but I meant more if it was possible with the current code at all? Correct me if I'm wrong but I'm guessing from your answer that its "No".

**Comment by TNikolai** [comment]
Prepared new pullRequest with this feature.

**Comment by michaelkamphausen** [comment]
Looks good! Thanks.
Feature is released with version 0.1.3.
