### ISSUE TITLE
Height Becomes 0 When Putting Label Inside StackView

### ISSUE THREAD

**Issue by wilbertliu** [apploft/ExpandableLabel#18]
Hello,

I was using `ExpandableLabel` on a vertical `StackView` with these configurations : 
- Alignment `Fill`
- Distribution `Fill`

I just changed these `ExpandableLabel` properties through storyboard :
- Collapsed `On`
- Text `bla bla bla`
- Lines `3`

When I ran the app, the label shows nothing.
Do you have any suggestions?

Thanks!

**Comment by GabriellaBLopes** [comment]
I am experiencing the same issue using ExpandableLabel in a Scroll View.

**Comment by Lausbert** [comment]
The demo app builds and runs without issues on iOS 11.
Scrollviews and stackviews case are not officially supported by this project, it was developed with regard to tableview cells. Issues regarding scrollviews and stackviews are probably not related to iOS 11.

If you like to add scrollview support, feel free to send a pull request.
