### ISSUE TITLE
Error with setLessLinkWith

### ISSUE THREAD

**Issue by nevinjethmalani** [apploft/ExpandableLabel#19]
I am getting an error "is inaccessible due to internal protection level" when trying to access the method setLessLinkWith. Did you not make this public?

**Comment by kevinlg** [comment]
I am encountering the same error.

**Comment by nevinjethmalani** [comment]
I am pretty sure it is a simple fix on your end. Assuming the function works, you just need to make it accessible when installed through cocoa pods.

**Comment by michaelkamphausen** [comment]
This is fixed with version 0.1.6.
