### ISSUE TITLE
Tapping label does nothing

### ISSUE THREAD

**Issue by nevinjethmalani** [apploft/ExpandableLabel#20]
If an Expandable Label is in a tableview cell and a user taps the Expandable Label, "didselectrow" at index path is not called. It does not allow us to select a cell if a user taps on the Expandable Label within that cell.

**Comment by michaelkamphausen** [comment]
This is intended, as a view is not responsible for managing it's superview. Same applies to a UIButton in a UITableViewCell.
You should implement the ExpandableLabelDelegate protocol's `didExpandLabel` and `didCollapseLabel` methods and then implement whatever you like to do when a cell is tapped in these.

**Comment by jkritikos** [comment]
@michaelkamphausen Are you sure this is still the case? Having looked at your implementation, it seems that these delegation methods are fired when the user taps on 'More' - not on the entire label.

**Comment by michaelkamphausen** [comment]
The delegate methods should be fired when the user expands or collapses the label. I don't know the details of the implementation, because it's actually not my code and I only take the time to maintain pull requests.
