### ISSUE TITLE
CLOSE added to all cells in a tableView

### ISSUE THREAD

**Issue by jflaurin** [apploft/ExpandableLabel#22]
I use the ExpandableLabel in a tableview, when I press on MORE in one of the CELL then all my cells have the red CLOSE in them, even those that didn't need to expand

**Comment by michaelkamphausen** [comment]
I can't reproduce this problem. Have a look at the demo project, especially the ViewController class. You need to track the open/close state of your cells in your code and set it on the ExpandableLabel when dequeueing reusable cells.
