### ISSUE TITLE
collapsedAttributedLink often disappears upon device rotation

### ISSUE THREAD

**Issue by n3d1117** [apploft/ExpandableLabel#30]
Tested straight from Demo project in iPhone 6 Simulator.

Here's portrait, working fine:
<img width="374" alt="screen shot 2017-08-04 at 16 16 30" src="https://user-images.githubusercontent.com/11541888/28973199-dab38a66-7932-11e7-90df-fdd703e3b53b.png">

Here's landscape, "... more" disappeared:
<img width="663" alt="screen shot 2017-08-04 at 16 16 49" src="https://user-images.githubusercontent.com/11541888/28973200-dad74082-7932-11e7-92ec-0a52d306d617.png">

**Comment by michaelkamphausen** [comment]
should be fixed by #33
