### ISSUE TITLE
collapsedAttributedLink & expandedAttributedLink issue

### ISSUE THREAD

**Issue by khetaram** [apploft/ExpandableLabel#31]
Hi,
collapsedAttributedLink is not shown when i set number of line for label to 1 and expandedAttributedLink is not showing always. On tab of label expand and shrink is working but collapsedAttributedLink and expandedAttributedLink text is not shown.  I have tried the same demo from github in that also it is not displaying. I have tried setLessLinkWith also.

**Comment by michaelkamphausen** [comment]
should be fixed by #33
