### ISSUE TITLE
Support for Swift 4

### ISSUE THREAD

**Issue by nevinjethmalani** [apploft/ExpandableLabel#34]
Does this project support swift 4? If not, when do you think you will have a version for swift 4 available?

**Comment by michaelkamphausen** [comment]
You can try the [swift4](https://github.com/apploft/ExpandableLabel/tree/swift4) branch.

**Comment by jethmalani** [comment]
When will you merge this into master if ever?

**Comment by michaelkamphausen** [comment]
Have you tried the [swift4](https://github.com/apploft/ExpandableLabel/tree/swift4) branch? Have you experienced any issues with it?

**Comment by nevinjethmalani** [comment]
I have tried it but I have not done any in-depth testing. It worked in a very basic test case but I think I did see an issue in one situation. I will look into it further and get back to you.
