### ISSUE TITLE
Not working in iOS 11

### ISSUE THREAD

**Issue by jethmalani** [apploft/ExpandableLabel#36]
I am having issues implementing this in my VC in iOS 11. Do you know if there are any issues when using this project in iOS 11? I have the expandable label in a scrollview not a tableview like in the demo.

**Comment by michaelkamphausen** [comment]
The demo app builds and runs without issues on iOS 11.

The scrollview case is not officially supported by this project, it was developed with regard to tableview cells. Issues regarding scrollviews are probably not related to iOS 11.

If you like to add scrollview support, feel free to send a pull request.
