### ISSUE TITLE
Need this code with objective c support

### ISSUE THREAD

**Issue by ruchiteasternts17Dec** [apploft/ExpandableLabel#37]
Hello 

I want this code with objective c if you possible else suggest me other library

**Comment by michaelkamphausen** [comment]
You can use swift components from objective-c code, though this has not been tested for this project. See [Apples Documentation on Mix and Match Interoperability](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html).
