### ISSUE TITLE
How do I bridge this with objective c?

### ISSUE THREAD

**Issue by hardikamal** [apploft/ExpandableLabel#39]
Hi,

Can you put up an example of bridging this with objective c code?

Thanks

**Comment by michaelkamphausen** [comment]
Read [Apples Documentation on Mix and Match Interoperability](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html). In addition, you will find lots of examples when you do your research.

**Comment by hardikamal** [comment]
I followed the documentation but i am not able to access the expandablelabel delegate of swift from objective c. How can i access that??

**Comment by michaelkamphausen** [comment]
The delegate cannot be accessed from objective-c code. If you need the delegate, you have to access it with swift.

**Comment by hardikamal** [comment]
any way where i can access that delegate in objective c?

**Comment by michaelkamphausen** [comment]
No.

**Comment by hardikamal** [comment]
Anyways I did it myself.

**Comment by sabeenlabs** [comment]
> Anyways I did it myself.

How did you solve this
