### ISSUE TITLE
Does not works with iPhone 5s

### ISSUE THREAD

**Issue by pawarlalit29** [apploft/ExpandableLabel#43]
Hi
Read more does not comes at first load, after scrolling it appears this problem only occurs in iPhone 5s and below.
Also the last item get automatically collapsed on expanding it.
How can i solve this pls help.

Thanks

**Comment by hardikamal** [comment]
+1

**Comment by c0state** [comment]
I noticed this as well. The `collapsedAttributedLink` won't show on this form factor. Not sure if there's a bug in the calculations due to the smaller width. Did you find a solution?

**Comment by mxp7064** [comment]
Similar problem on iphone 6 both simulator and real device. MORE is sometimes missing and LESS link is sometimes not working

**Comment by manikantanarne** [comment]
@pawarlalit29 Did you got the solution?
