### ISSUE TITLE
collapsedAttributedLink alpha color has reduce 

### ISSUE THREAD

**Issue by Pakkapon** [apploft/ExpandableLabel#74]
I try to set color to collapsedAttributedLink  but it's look like alpha got reduce or something wrong with color 

var attributes = [NSAttributedString.Key: AnyObject]()
attributes[.foregroundColor] = UIColor.blue 
let attributedString = NSAttributedString(string: "More", attributes: attributes)

label.collapsedAttributedLink = attributedString

What I am doing wrong?  Suggest me please

**Comment by jack-le-shopback** [comment]
I got the same issue too. How did you solve it ?

**Comment by vijayladvainnopadsolutions** [comment]
This is working for me

let attributes : [NSAttributedString.Key: Any] = [
            .foregroundColor: UIColor.blue
        ]
let attributedString = NSAttributedString(string: "More", attributes: attributes)
label.collapsedAttributedLink = attributedString

**Comment by bmladva** [comment]
let attributes : [NSAttributedString.Key: Any] = [
            .foregroundColor: UIColor.blue
        ]
        
let attributedString = NSAttributedString(string: "More", attributes: attributes)
label.collapsedAttributedLink = attributedString

Hope it's help
