### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by aminasadi0** [apploft/ExpandableLabel#8]
Hey,

Any plan to support Swift 3.0?

Bests

**Comment by michaelkamphausen** [comment]
Hi,
yes, I just merged #6 with Swift 3 support by @czgarrett and released version 0.1.0.

**Comment by devender54321** [comment]
use
  pod 'ExpandableLabel', '~> 0.1.0' 

for Swift3

**Comment by devender54321** [comment]
pod 'ExpandableLabel', '~> 0.1.0'   for Swift3
