### ISSUE TITLE
Read more button initially doesn't show.

### ISSUE THREAD

**Issue by DucAnTrn** [apploft/ExpandableLabel#94]
Read more button appear after dequeue in UItableView, initially it doesn't show some first cell. but if I scrolling down and scroll back it back to normal. how I can fix this problem ?

**Comment by cemnisan** [comment]
Hey, @DucAnTrn I have same issue. Did you solve it?

**Comment by Jeet000007** [comment]
Issue arises when try setting 'More' text from cell for row method . 
try using common init method of library and do customisation there itself . 
Check my cell for row method and part that is commented 
*Not a permanent fix but might help for time being

 func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "PlansTableCell") as! PlansTableCell
        
        cell.titleLabel.text = "Validity 28 Days"
        
        cell.planDescription.tag = indexPath.row
        
        cell.planDescription.delegate = self
        cell.planDescription.numberOfLines = 2
        cell.planDescription.shouldCollapse = true
        if indexPath.row % 2 == 0{
            cell.planDescription.text = getAnotherPlanText()
        }else{
            cell.planDescription.text = getPlanText()
        }
        
        
        cell.planDescription.collapsed = collapsStateArray[indexPath.row]
//        let myAttribute = [ NSAttributedString.Key.foregroundColor: UIColor.red,NSAttributedString.Key.font : UIFont.systemFont(ofSize: 16, weight: .semibold) ]
//        cell.planDescription.collapsedAttributedLink = NSAttributedString(string: "...more",attributes: myAttribute)
//        cell.planDescription.setLessLinkWith(lessLink: "n", attributes: [.foregroundColor:UIColor.red], position: .left)
//        cell.planDescription.ellipsis = NSAttributedString(string: "",attributes: myAttribute)
        cell.layoutIfNeeded()
        return cell
    }
